<a href="https://colab.research.google.com/github/irfandziki/Data-Mining/blob/master/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [15]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [16]:
print(x)

[['Sunny' 85.0 85.0]
 ['Sunny' 80.0 90.0]
 ['Overcast' 83.0 78.0]
 ['Rain' 70.0 96.0]
 ['Rain' 68.0 nan]
 ['Rain' 65.0 70.0]
 ['Overcast' 64.0 65.0]
 ['Sunny' nan 95.0]
 ['Rain' 75.0 80.0]
 ['Sunny' 75.0 70.0]]


In [17]:
print(y)

['no' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'yes']


In [21]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [22]:
print(x)

[['Sunny' 85.0 85.0]
 ['Sunny' 80.0 90.0]
 ['Overcast' 83.0 78.0]
 ['Rain' 70.0 96.0]
 ['Rain' 68.0 81.0]
 ['Rain' 65.0 70.0]
 ['Overcast' 64.0 65.0]
 ['Sunny' 73.88888888888889 95.0]
 ['Rain' 75.0 80.0]
 ['Sunny' 75.0 70.0]]


In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [25]:
print(x)

[[0.0 0.0 1.0 85.0 85.0]
 [0.0 0.0 1.0 80.0 90.0]
 [1.0 0.0 0.0 83.0 78.0]
 [0.0 1.0 0.0 70.0 96.0]
 [0.0 1.0 0.0 68.0 81.0]
 [0.0 1.0 0.0 65.0 70.0]
 [1.0 0.0 0.0 64.0 65.0]
 [0.0 0.0 1.0 73.88888888888889 95.0]
 [0.0 1.0 0.0 75.0 80.0]
 [0.0 0.0 1.0 75.0 70.0]]


In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [27]:
print(y)

[0 0 1 1 1 0 1 0 1 1]


In [29]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [30]:
print(x_train)

[[1.0 0.0 0.0 64.0 65.0]
 [0.0 1.0 0.0 68.0 81.0]
 [0.0 0.0 1.0 85.0 85.0]
 [0.0 1.0 0.0 70.0 96.0]
 [0.0 0.0 1.0 80.0 90.0]
 [0.0 0.0 1.0 73.88888888888889 95.0]
 [0.0 1.0 0.0 75.0 80.0]
 [0.0 1.0 0.0 65.0 70.0]]


In [31]:
print (x_test)

[[1.0 0.0 0.0 83.0 78.0]
 [0.0 0.0 1.0 75.0 70.0]]


In [32]:
print (y_train)

[1 1 0 1 0 0 1 0]


In [33]:
print (y_test)

[1 1]


In [34]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [35]:
print(x_train)

[[1.0 0.0 0.0 -1.2567613468357999 -1.7006292919168278]
 [0.0 1.0 0.0 -0.6729754308862672 -0.16766767666785626]
 [0.0 0.0 1.0 1.8081147118992464 0.21557272714438663]
 [0.0 1.0 0.0 -0.38108247291150094 1.2694838376280546]
 [0.0 0.0 1.0 1.0783823169623306 0.6946232319096902]
 [0.0 0.0 1.0 0.18648716759498868 1.1736737366749939]
 [0.0 1.0 0.0 0.3486499220254149 -0.263477777620917]
 [0.0 1.0 0.0 -1.1108148678484167 -1.2215787871515242]]


In [36]:
print (x_test)

[[1.0 0.0 0.0 1.5162217539244802 -0.45509797952703845]
 [0.0 0.0 1.0 0.3486499220254149 -1.2215787871515242]]
